# Generated by Django 4.2.7 on 2025-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SELLER'), (2, 'CUSTOMER')], null=True),
        ),
    ]
